# Generated by Django 5.0.6 on 2024-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
