# Generated by Django 5.0.6 on 2024-05-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0004_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
    ]
